### PR TITLE
Responsive issue fixed

### LINKED ISSUE #2: [style 🎨] Phones & Tablets Responsive
Try to make users user-friendly with both platforms like mobile phones, tablets, and also desktop mode.

**Note:** I use [Shadcn UI](https://ui.shadcn.com/) library so before your contribution you have to know about this. feel free to check [shadcn](https://ui.shadcn.com) documentation.

### PR DESCRIPTION
**Pull request by ahammedhridoy**
### Description

I have resolved the problem with the website's responsiveness on both tablet and mobile devices.

### Fixes #2 

image

image

### Type of change

- [x] Style Added (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

File: src/components/contents/ProfileCard.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const ProfileCard = ({
           <AvatarFallback>{name.substring(0, 2).toUpperCase()}</AvatarFallback>
         </Avatar>
         <div className="flex-start w-full overflow-hidden flex-col gap-1">
-          <h2 className="text-2xl font-semibold text-gray-700 dark:text-zinc-200">
+          <h2 className="lg:text-2xl font-semibold text-gray-700 dark:text-zinc-200 text-1xl">
```
Comment (devlopersabbir) [inline src/components/contents/ProfileCard.tsx:32]: In tailwind there are no one classname that is `text-1xl`
I think it will be `text-xl`

**Review by devlopersabbir — APPROVED** [review]
